import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import LenisProvider from "@/provider/LenisProvider.tsx";

export const metadata: Metadata = {
  title: "Quanta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Préconnexion Google Fonts pour accélérer le chargement */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Onest:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Header />
        <main>
          <LenisProvider>
            {children}
          </LenisProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
