import type { Metadata } from "next";
import "../styles/globals.css";
import Header from "@/components/shared/header";

export const metadata: Metadata = {
  title: "Quanta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
